### ISSUE TITLE
Quick access to guidelines

### ISSUE THREAD

**Issue by SardarAmiri** [SardarAmiri/TripSafe#3]
User Story 3
As a teacher, I want quick access to guidelines, so that I can plan trips efficiently.
**Acceptance Criteria**

- [x] The homepage must include a link to teacher resources.
- [x] A brief description of the resource categories (e.g., supervision tips, and preparation checklist) must be displayed.

**Tasks**

- [x] Write a few bullet points of the teacher guidelines available.
- [x] Add a link labelled “Explore Teacher Guidelines” directing to the "Guidelines & Resources" Modal.
